# PROJECT: dolphin
# VERSION: 1.0.0
# Author: wangxiang4

version: '3'
services:
  # 生产环境nacos配置
  nacos:
    image: nacos/nacos-server:2.0.0
    hostname: kicc-register
    container_name: nacos
    restart: always
    env_file:
      - nacos/.env
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    volumes:
      - /usr/software/dockerDatabase/nacos/logs:/home/nacos/logs
      - /usr/software/dockerDatabase/nacos/data:/home/nacos/data
      - nacos_conf:/home/nacos/conf

  # register配置
  dolphin-register:
    build:
      context: ../dolphin-register
    restart: always
    container_name: dolphin-register
    hostname: dolphin-register
    image: dolphin-register
    ports:
      - 8848:8848
      # 服务端口,注意通过阅读官方文档,发现nacos2.x使用docker部署时一定要保持映射端口一致
      #	不一样会出现本地服务访问不了服务端nacos: https://nacos.io/zh-cn/docs/2.0.0-compatibility.html
      # 经过测试使用docker部署时候,还需要开启对应供应商服务器的防火墙端口,不开第三方外部客户端连不上,会报错
      - 9848:9848
      - 9849:9849

  # gateway配置
  dolphin-gateway:
    build:
      context: ../dolphin-gateway
    container_name: dolphin-gateway
    image: dolphin-gateway
    hostname: dolphin-gateway
    restart: always
    ports:
      - 9999:9999

  # oauth2.0配置
  dolphin-auth:
    build:
      context: ../dolphin-auth
    container_name: dolphin-auth
    environment:
      GATEWAY_HOST: xxx.xxx.xxx.xxx
    image: dolphin-auth
    hostname: dolphin-auth
    restart: always
    ports:
      - 3000:3000

  # system-biz配置
  dolphin-system:
    build:
      context: ../dolphin-platform/dolphin-platform-biz/dolphin-system-biz
    container_name: dolphin-system
    environment:
      GATEWAY_HOST: xxx.xxx.xxx.xxx
    image: dolphin-system-biz
    hostname: dolphin-system
    restart: always
    ports:
      - 4000:4000

  # common-biz配置
  dolphin-common:
    build:
      context: ../dolphin-platform/dolphin-platform-biz/dolphin-common-biz
    container_name: dolphin-common
    environment:
      GATEWAY_HOST: xxx.xxx.xxx.xxx
    image: dolphin-common-biz
    hostname: dolphin-common
    restart: always
    ports:
      - 8000:8000

  # monitor-biz配置
  dolphin-monitor:
    build:
      context: ../dolphin-platform/dolphin-platform-biz/dolphin-monitor-biz
    container_name: dolphin-monitor
    environment:
      GATEWAY_HOST: xxx.xxx.xxx.xxx
    image: dolphin-monitor-biz
    hostname: dolphin-monitor
    restart: always
    ports:
      - 6000:6000

  # 新建业务工程docker-compose模板
  # 注释命名规范:【xxx-biz】
  # 名称命名规范:【dolphin-xxx】
  dolphin-template:
    build:
      context: ../dolphin-platform/dolphin-platform-biz/dolphin-template-biz
    container_name: dolphin-template
    image: dolphin-template-biz
    hostname: dolphin-template
    restart: always
    ports:
      - 1111:1111

  # rocketmq-visual-dashboard配置
  dolphin-visual-rocketmq:
    build:
      context: ../dolphin-visual/dolphin-rocketmq-dashboard
    container_name: dolphin-visual-rocketmq
    image: dolphin-rocketmq-dashboard
    hostname: dolphin-visual-rocketmq
    restart: always
    ports:
      - 8058:8058

  # sentinel-visual-dashboard配置
  dolphin-visual-sentinel:
    build:
      context: ../dolphin-visual/dolphin-sentinel-dashboard
    container_name: dolphin-visual-sentinel
    image: dolphin-sentinel-dashboard
    hostname: dolphin-visual-sentinel
    restart: always
    ports:
      - 8056:8056

  # dolphin-visual-job配置
  dolphin-visual-job:
    build:
      context: ../dolphin-visual/dolphin-xxl-job-admin
    container_name: dolphin-visual-job
    image: dolphin-xxl-job-admin
    hostname: dolphin-visual-job
    restart: always
    ports:
      - 8057:8057

  # spring-admin配置
  dolphin-visual-spring:
    build:
      context: ../dolphin-visual/dolphin-spring-dashboard
    container_name: dolphin-visual-spring
    restart: always
    image: dolphin-spring-dashboard
    hostname: dolphin-visual-spring
    ports:
      - 8061:8061

volumes:
  nacos_conf:
    driver: local
